<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="GioiThieu.aspx.cs" Inherits="Project.GioiThieu" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div id="dnn_ctr2943_HtmlModule_lblContent" class="Normal" style ="margin: 10px 10px">
        <p style="text-align: center;"><img src="Images/gioithieu.jpg" style="width: 640px; height: 424px;" /></p>
        <p style="text-align: justify;"><strong><span style="color: #ff0000;"></span></strong></p>
        <p style="text-align: justify;">&nbsp;</p>
        <p style="text-align: justify;"><strong><span style="color: red;">SỨ MẠNG:</span></strong><strong><span> </span></strong><span style="color: #000099;">Trường Đại học Vinh là cơ sở&nbsp;giáo dục đại học&nbsp;đào tạo nguồn nhân lực chất lượng cao; là trung tâm đào tạo, bồi dưỡng giáo viên, nghiên cứu khoa học giáo dục, khoa học cơ bản, ứng dụng và chuyển giao công nghệ hàng đầu của khu vực Bắc Trung Bộ và cả nước, luôn hướng tới sự thành đạt của người học.</span></p>
        <p style="text-align: justify;"><strong><span>&nbsp;</span></strong></p>
        <p style="text-align: justify;"><strong><span style="color: red;">TẦM NHÌN:</span></strong><strong><span> </span></strong><span style="color: #000099;">Trường Đại học Vinh trở thành Đại học Vinh trọng điểm quốc gia, thành viên của Mạng lưới các trường đại học ASEAN.</span></p>
        <p style="text-align: justify;"><strong><span>&nbsp;</span></strong></p>
        <p style="text-align: justify;"><strong><span style="color: red;">MỤC TIÊU TỔNG QUÁT:</span></strong><strong><span> </span></strong><span style="color: #000099;">Tạo dựng môi trường học thuật tốt để hình thành, phát triển phẩm chất và năng lực cá nhân, hướng tới sự thành công.</span></p>
        <p style="text-align: justify;"><strong><span>&nbsp;</span></strong></p>
        <p style="text-align: justify;"><strong><span style="color: red;">GIÁ TRỊ CỐT LÕI</span></strong></p>
        <p style="text-align: justify;"><strong><span>&nbsp;</span></strong></p>
        <p style="text-align: justify;"><strong><span style="color: #006600;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Trung thực&nbsp;</span></strong><em><span style="color: #006600;">(Honesty)</span></em></p>
        <p style="text-align: justify;"><strong><span style="color: #006600;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Trách nhiệm&nbsp;</span></strong><em><span style="color: #006600;">(Accountability)</span></em></p>
        <p style="text-align: justify;"><strong><span style="color: #006600;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Say mê&nbsp;</span></strong><em><span style="color: #006600;">(Passion)</span></em></p>
        <p style="text-align: justify;"><strong><span style="color: #006600;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sáng tạo&nbsp;</span></strong><em><span style="color: #006600;">(Creativity)</span></em></p>
        <p style="text-align: justify;"><strong><span style="color: #006600;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hợp tác&nbsp;</span></strong><em><span style="color: #006600;">(</span></em><em><span style="color: #006600;">Collaboration)</span></em></p>
        <p style="text-align: justify;"><em><span>&nbsp;</span></em></p>
        <p style="text-align: justify;"><strong><span style="color: red;">TRIẾT LÝ GIÁO DỤC</span></strong></p>
        <p style="text-align: justify;"><strong><span style="color: #0070c0;">&nbsp;</span></strong></p>
        <p style="text-align: center;"><strong><span style="color: #006600;">HỢP TÁC -&nbsp; SÁNG TẠO</span></strong></p>
        <p style="text-align: justify;"><span>&nbsp;</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Trường Đại học Vinh xác định <strong><em>Hợp tác</em></strong><em> (Collaboration)</em> trong môi trường học thuật, đa văn hóa là sự kết nối, tương tác và cộng hưởng năng lực giữa các cá nhân và giữa các đơn vị, tổ chức để tạo nên sự phát triển. <em>Hợp tác</em> là tôn trọng sự khác biệt, sự phát triển tự do của mỗi con người, thể hiện tính nhân văn. <em>Hợp tác</em> là con đường để cùng phát triển và đảm bảo lợi ích hài hòa của các bên liên quan. </span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Nhà trường tạo dựng môi trường hợp tác để thực hiện các hoạt động đào tạo, nghiên cứu khoa học và phục vụ cộng đồng. Người học được khuyến khích phát triển năng lực hợp tác thông qua chương trình đào tạo với các phương pháp dạy học tích cực chú trọng đến năng lực hợp tác </span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Trường Đại học Vinh coi <strong><em>Sáng tạo</em></strong><em> (Creativity)</em> là năng lực cốt lõi nhất của mỗi cá nhân, đảm bảo cho sự thành công trong nghề nghiệp và cuộc sống trong bối cảnh thay đổi và sự vận động của Cách mạng công nghiệp 4.0, đảm bảo khả năng học suốt đời. <em>Sáng tạo</em> là tạo ra những tri thức và giá trị mới. <em>Sáng tạo</em> là dám nghĩ, dám làm, say mê nghiên cứu, khám phá, và không ngừng cải tiến. </span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Nhà trường đào tạo người học trở thành người lao động sáng tạo thông qua quá trình <em>"hình thành ý tưởng - thiết kế - triển khai - vận hành"</em> trong các hoạt động nghề nghiệp, có khả năng thích ứng cao trong thế giới việc làm.</span></p>
        <p style="text-align: justify;"><span>&nbsp;</span></p>
        <p style="text-align: justify;"><strong><span style="color: red;">CHÍNH SÁCH ĐẢM BẢO CHẤT LƯỢNG</span></strong></p>
        <p style="text-align: justify;"><span style="color: #000099;">Trường Đại học Vinh cam kết cung cấp cho xã hội nguồn nhân lực chất lượng cao, đảm bảo các công trình nghiên cứu khoa học có chất lượng và chuyển giao các kết quả nghiên cứu ứng dụng cho các tổ chức, địa phương bằng các biện pháp:</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">1. Không ngừng cải tiến chất lượng trên cơ sở đổi mới chương trình đào tạo và phương pháp dạy học;&nbsp;</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">2. Tạo môi trường học tập, nghiên cứu và điều kiện làm việc cho người học, giảng viên và cán bộ viên chức của Nhà trường, lấy người học làm trung tâm, đội ngũ giảng viên là nguồn lực cốt lõi trong hoạt động đào tạo và nghiên cứu khoa học;</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">3. Thường xuyên đánh giá và cải tiến cách thức, phương pháp quản lý nhằm nâng cao hiệu lực, hiệu quả quản lý hoạt động của Nhà trường.</span></p>
        <p style="text-align: justify;"><span>&nbsp;</span></p>
        <p style="text-align: center;"><span>*</span></p>
        <p style="text-align: center;"><span>*&nbsp;&nbsp;&nbsp;&nbsp; *</span></p>
        <p><span>&nbsp;</span></p>
        <p style="text-align: center;"><strong><span style="color: red;">TRƯỜNG ĐẠI HỌC VINH GIỚI THIỆU</span></strong></p>
        <p style="text-align: justify;"><span>&nbsp;</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Trường Đại học Vinh được thành lập từ năm 1959. Trải qua 60 năm xây dựng và phát triển, từ một trường đại học sư phạm đến nay Trường đã trở thành một trường đại học đa ngành và đa lĩnh vực. Nhà trường vinh dự là trường đại học đầu tiên của Trung ương đóng trên quê hương Chủ tịch Hồ Chí Minh vĩ đại, mảnh đất địa linh nhân kiệt, có truyền thống hiếu học, yêu nước và cách mạng.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Ra đời trong những năm tháng ác liệt của cuộc kháng chiến chống Mỹ cứu nước, Trường Đại học Vinh đã trải qua những chặng đường phát triển vô cùng gian khổ nhưng cũng rất đỗi vinh quang. Trong cuộc chiến tranh phá hoại của Đế quốc Mỹ gây ra đối với Miền Bắc, Nhà trường đã trải qua 8 năm sơ tán, gian nan tột bậc, chịu tổn thất nặng nề nhất trong hệ thống các trường đại học. Đến năm 1973, Nhà trường mới quay trở lại thành phố Vinh và phải xây dựng lại hoàn toàn. Trong những năm tháng khó khăn chung của đất nước trước đổi mới, Nhà trường đã ra sức khắc phục mọi khó khăn, thử thách, bằng ý chí tự lực tự cường, dù trong bất cứ hoàn cảnh nào cũng thi đua dạy tốt, học tốt. Từ những năm 1990, tiếp thu tinh thần đổi mới của Đảng, đường lối, chính sách của Nhà nước, Nhà trường đã từng bước ổn định và mở rộng phát triển theo hướng đa ngành. Năm 2001, ghi nhận những nỗ lực và cố gắng của tập thể Nhà trường trong việc chuyển từ một trường đại học sư phạm trở thành một trường đại học đa ngành, đào tạo nhân lực, bồi dưỡng nhân tài cho khu vực Bắc Trung Bộ và cả nước, Thủ tướng Chính phủ đã quyết định đổi tên Trường Đại học Sư phạm Vinh thành Trường Đại học Vinh. Tháng 7 năm 2011, Thủ tướng Chính phủ đã bổ sung Trường Đại học Vinh vào danh sách xây dựng thành trường đại học trọng điểm Quốc gia. Hiện nay, Trường Đại học Vinh là 1 trong 8 trung tâm đào tạo, bồi dưỡng giáo viên và cán bộ quản lý giáo dục; là 1 trong 5 trung tâm kiểm định chất lượng giáo dục của cả nước; là 1 trong 10 trường tham gia Đề án Ngoại ngữ Quốc gia. Trường được công nhận đạt tiêu chuẩn kiểm định chất lượng giáo dục vào năm 2017.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Cơ cấu tổ chức của Trường hiện có 6 viện, 7 khoa đào tạo, 12 phòng ban, 12 trung tâm, trạm, 2 văn phòng đại diện với 55 ngành đào tạo đại học;&nbsp;37 chuyên ngành đào tạo thạc sĩ và 17 chuyên ngành đào tạo tiến sĩ&nbsp;với trên 40.000 sinh viên, học viên, nghiên cứu sinh.&nbsp;Trường THPT Chuyên trực thuộc Trường Đại học Vinh là 1 trong 20 trường trung học phổ thông có uy tín nhất trong cả nước. Trường Thực hành Sư phạm Đại học Vinh với các cấp học mầm non, tiểu học và trung học cơ sở là một trong những cơ sở giáo dục có uy tín nhất trên địa bàn thành phố Vinh.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Từ khi thành lập đến nay, Nhà trường đã đào tạo và cung cấp cho khu vực Bắc Trung Bộ và cả nước trên 180.000 cử nhân sư phạm, cử nhân khoa học, kỹ sư; 13.366 thạc sĩ và 244 tiến sĩ.&nbsp;Tỷ lệ sinh viên tốt nghiệp có việc làm chiếm trên 80%. Sinh viên tốt nghiệp từ Trường Đại học Vinh được đào tạo toàn diện về chuyên môn nghiệp vụ, kỹ năng làm việc, kỹ năng sống... nên khi ra trường sớm khẳng định được năng lực chuyên môn, được các nhà tuyển dụng đánh giá cao. Nhiều cựu sinh viên của Trường đã trở thành các nhà khoa học, chuyên gia đầu ngành, cán bộ quản lý tại các cơ sở giáo dục, đào tạo, các viện nghiên cứu, các trung tâm khoa học, công nghệ, kinh tế lớn trong nước và quốc tế.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Cùng với hoạt động đào tạo,&nbsp;Nhà trường luôn quan tâm hoạt động nghiên cứu khoa học và hợp tác quốc tế.&nbsp;Đội ngũ giảng viên tích cực tham gia các dự án khoa học - công nghệ của Chính phủ, các đề tài, nhiệm vụ nghiên cứu cấp Bộ, cấp Nhà nước. Nhà trường có quan hệ hợp tác đào tạo, nghiên cứu khoa học, bồi dưỡng cán bộ với hàng chục cơ sở giáo dục đại học, các tổ chức khoa học quốc tế từ Châu Âu, Châu Á, Châu Mỹ và Châu Úc. Trong những năm gần đây, Nhà trường đã chủ trì tổ chức nhiều hội thảo khoa học khu vực và quốc tế; tạo lập được các nhóm nghiên cứu với các nhà khoa học đầu ngành. Chỉ tính trong 5 năm gần đây, Trường triển khai hàng trăm đề tài khoa học các cấp; tổ chức trên 100 hội thảo khoa học; có trên 2.000 bài báo của cán bộ được công bố ở các tạp chí khoa học trong và ngoài nước. Trường luôn nằm trong tốp 10 trường đại học có bài công bố quốc tế nhiều nhất ở Việt Nam.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Với phương châm: <em>"Nuôi dưỡng say mê - Khuyến khích sáng tạo - Tôn trọng khác biệt - Thúc đẩy hợp tác"</em>,&nbsp;trải qua 60 năm xây dựng và phát triển, từ 17 cán bộ giảng dạy và một số cán bộ hành chính đầu tiên, đến nay Trường có 1.046 cán bộ, viên chức&nbsp;(trong đó có 731 cán bộ giảng dạy), 56 giảng viên cao cấp, 4 giáo sư, 59 phó giáo sư, 256 tiến sĩ, 504 thạc sĩ. Chất lượng đội ngũ cán bộ hiện nay của Nhà trường đáp ứng và vượt mức bình quân chung của cả nước.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Về cơ sở vật chất, với sự quan tâm đầu tư của Chính phủ, Bộ Giáo dục và Đào tạo và sự giúp đỡ của tỉnh Nghệ An, tỉnh Hà Tĩnh, Trường Đại học Vinh hiện nay có hệ thống cơ sở vật chất hiện đại, cơ bản đáp ứng được yêu cầu của Nhà trường trong thời kỳ hội nhập.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Đảng bộ Trường Đại học Vinh là đảng bộ cơ sở trực thuộc Đảng bộ tỉnh Nghệ An. Hiện nay, Đảng bộ có </span><span style="color: #000099;">10 đảng bộ bộ phận, 42 chi bộ (trong đó có 13 chi bộ cán bộ, 10 chi bộ học viên, sinh viên trực thuộc đảng bộ bộ phận, 19 chi bộ trực thuộc Đảng bộ Trường). Toàn Đảng bộ có 923 đảng viên, trong đó có 626 cán bộ, 297 sinh viên, học viên cao học. </span><span style="color: #000099;">Đảng bộ Nhà trường nhiều năm liên tục được công nhận là Đảng bộ trong sạch, vững mạnh.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Với những kết quả toàn diện trong 60 năm xây dựng và phát triển, tập thể Nhà trường, các đơn vị và cá nhân trong Trường đã được tặng nhiều phần thưởng cao quý: Danh hiệu Anh hùng Lao động trong thời kỳ đổi mới (năm 2004), Huân chương Độc lập hạng Nhất (năm 2009, năm 2014), Huân chương Lao động hạng Nhất (năm 1992, năm 2019), Huân chương Lao động hạng Ba của Nước Cộng hoà dân chủ nhân dân Lào (năm 2019), Huân chương Hữu nghị của Nước Cộng hoà dân chủ nhân dân Lào (năm 2009, năm 2011 và năm 2017) và nhiều phần thưởng cao quý khác.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Với bề dày truyền thống 60 năm, Nhà trường luôn lấy chất lượng đào tạo giáo viên, chất lượng của một trường sư phạm mẫu mực làm động lực cho sự phát triển. Nghị quyết Đại hội Đảng bộ Trường lần thứ XXXI đã xác định phương hướng phát triển của Nhà trường trong nhiệm kỳ 2015 - 2020 là:&nbsp;<em>"Tiếp tục đổi mới căn bản, toàn diện giáo dục và đào tạo; chủ động hội nhập quốc tế; xây dựng đội ngũ cán bộ đủ về số lượng, đảm bảo chất lượng, đồng bộ về cơ cấu; xây dựng Trường Đại học Vinh thành trường đại học trọng điểm, có một số ngành đạt tiêu chuẩn quốc tế, là thành viên của Mạng lưới các trường đại học ASEAN".</em></span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Hiện nay</span><span style="color: #000099;">, Nhà trường đang đổi mới căn bản công tác tổ chức và quản lý Nhà trường; </span><span style="color: #000099;">đẩy mạnh tái cấu trúc, ứng dụng công nghệ thông tin và truyền thông trong các hoạt động;</span><span style="color: #000099;"> triển khai xây dựng Chiến lược phát triển trường giai đoạn 2018 - 2025, tầm nhìn đến năm 2030; triển khai thực hiện Chiến lược phát triển </span><span style="color: #000099;">Khoa học và Công nghệ</span><span style="color: #000099;"> Trường Đại học Vinh giai đoạn 2018 - 2025</span><span style="color: #000099;">; </span><span style="color: #000099;">tiếp tục tổ chức tốt các hoạt động đào tạo</span><span style="color: #000099;">;</span><span style="color: #000099;"> tổ chức triển khai xây dựng và phát triển chương trình đào tạo đại học chính quy tiếp cận CDIO; </span><span style="color: #000099;">phối hợp để các cơ sở sản xuất, doanh nghiệp, các nhà tuyển dụng&nbsp;tham gia vào quá trình đào tạo; nâng cao chất lượng công tác thực hành, thí nghiệm, thực tập nghề nghiệp cho sinh viên, học viên;</span><span style="color: #000099;"> thực hiện phong trào</span><span style="color: #000099;"> thi đua</span><span style="color: #000099;"> </span><em><span style="color: #000099;">"</span></em><em><span style="color: #000099;">Đ</span></em><em><span style="color: #000099;">ổi mới, sáng tạo trong dạy và học"</span></em><span style="color: #000099;">; hướng tới tự chủ đại học.</span></p>
        <p style="text-align: justify;"><span style="color: #000099;">Trong những năm tới, mặc dầu tình hình kinh tế, xã hội của đất nước, khu vực và trên thế giới còn gặp nhiều khó khăn. Song tập thể cán bộ, viên chức và học sinh, sinh viên, học viên Trường Đại học Vinh vẫn luôn tin tưởng rằng dưới sự lãnh đạo sáng suốt của Đảng và Nhà nước, nhất định đất nước chúng ta sẽ vượt qua mọi thách thức, khó khăn, tiếp tục giành được nhiều thắng lợi trong sự nghiệp cách mạng, phần đấu sớm đưa nước ta cơ bản trở thành nước công nghiệp theo hướng hiện đại. Trên bước đường phát triển mạnh mẽ của đất nước, phát huy truyền thống tự lực tự cường, bằng tất cả trí tuệ, sáng tạo và niềm tin, Trường Đại học Vinh muốn được đóng góp nhiều hơn nữa cho sự nghiệp cách mạng của Đảng và của toàn dân tộc trên vị thế của đại học trọng điểm, trung tâm văn hoá, khoa học, giáo dục của khu vực và cả nước, xứng đáng là&nbsp;<em>"Ngọn cờ hồng trên quê hương Xô Viết"./.</em></span></p>
        &nbsp;
        <p style="text-align: center;"><span style="color: #000099;"><em><img src="Images/A0.jpg" style="width: 640px; height: 429px;"/><br>
        </em></span></p>
        
        <p style="text-align: right;"><span><strong><em>Cập nhật 01/01/2020</em></strong></span></p>
    </div>
</asp:Content>
